### ISSUE TITLE
Installing gherkin-official with pip, pickles is not included in the install

### ISSUE THREAD

**Issue by uchuugaka** [cucumber/gherkin-python#6] opened 2016-03-17 04:01 UTC
Installing gherkin-official with pip, pickles is not included in the install.
The directory for pickles is DEFINITELY on this repo, but it is not in the resulting installation, after `pip install gherkin-official` 

This is with 2.7.11 in a virtualenv with plenty of other things installed, on OS X 10.11.4

**Comment by aslakhellesoy** [comment] 2016-03-17 06:09
Dupe of https://github.com/cucumber/gherkin/pull/157 which will be in the next release

**Closed by aslakhellesoy** 2016-03-17 06:09 UTC
